//
// Generated file, do not edit! Created by opp_msgc 4.0 from Messages.msg.
//

#ifndef _MESSAGES_M_H_
#define _MESSAGES_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{ ... }} section:

#include "typedef.h"
// end cplusplus



/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeMsg extends cPacket {
 * };
 * </pre>
 */
class NlmeMsg : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeMsg&);

  public:
    NlmeMsg(const char *name=NULL, int kind=0);
    NlmeMsg(const NlmeMsg& other);
    virtual ~NlmeMsg();
    NlmeMsg& operator=(const NlmeMsg& other);
    virtual NlmeMsg *dup() const {return new NlmeMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, NlmeMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeNetworkFormation_request extends NlmeMsg {
 *     
 * 	
 * 	
 *     unsigned int ScanChannels;
 *     unsigned char ScanDuration;
 *     unsigned char BeaconOrder;
 *     unsigned char SuperframeOrder;
 *     unsigned short PANId;
 *     unsigned char BatteryLifeExtension;
 * };
 * </pre>
 */
class NlmeNetworkFormation_request : public NlmeMsg
{
  protected:
    unsigned int ScanChannels_var;
    unsigned char ScanDuration_var;
    unsigned char BeaconOrder_var;
    unsigned char SuperframeOrder_var;
    unsigned short PANId_var;
    unsigned char BatteryLifeExtension_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeNetworkFormation_request&);

  public:
    NlmeNetworkFormation_request(const char *name=NULL, int kind=0);
    NlmeNetworkFormation_request(const NlmeNetworkFormation_request& other);
    virtual ~NlmeNetworkFormation_request();
    NlmeNetworkFormation_request& operator=(const NlmeNetworkFormation_request& other);
    virtual NlmeNetworkFormation_request *dup() const {return new NlmeNetworkFormation_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getScanChannels() const;
    virtual void setScanChannels(unsigned int ScanChannels_var);
    virtual unsigned char getScanDuration() const;
    virtual void setScanDuration(unsigned char ScanDuration_var);
    virtual unsigned char getBeaconOrder() const;
    virtual void setBeaconOrder(unsigned char BeaconOrder_var);
    virtual unsigned char getSuperframeOrder() const;
    virtual void setSuperframeOrder(unsigned char SuperframeOrder_var);
    virtual unsigned short getPANId() const;
    virtual void setPANId(unsigned short PANId_var);
    virtual unsigned char getBatteryLifeExtension() const;
    virtual void setBatteryLifeExtension(unsigned char BatteryLifeExtension_var);
};

inline void doPacking(cCommBuffer *b, NlmeNetworkFormation_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeNetworkFormation_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeNetworkFormation_confirm extends NlmeMsg {
 *   	unsigned char status;  
 * };
 * </pre>
 */
class NlmeNetworkFormation_confirm : public NlmeMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeNetworkFormation_confirm&);

  public:
    NlmeNetworkFormation_confirm(const char *name=NULL, int kind=0);
    NlmeNetworkFormation_confirm(const NlmeNetworkFormation_confirm& other);
    virtual ~NlmeNetworkFormation_confirm();
    NlmeNetworkFormation_confirm& operator=(const NlmeNetworkFormation_confirm& other);
    virtual NlmeNetworkFormation_confirm *dup() const {return new NlmeNetworkFormation_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, NlmeNetworkFormation_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeNetworkFormation_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeNetworkDiscovery_request extends NlmeMsg {
 *     unsigned int ScanChannels;
 *     unsigned char ScanDuration;
 * };
 * </pre>
 */
class NlmeNetworkDiscovery_request : public NlmeMsg
{
  protected:
    unsigned int ScanChannels_var;
    unsigned char ScanDuration_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeNetworkDiscovery_request&);

  public:
    NlmeNetworkDiscovery_request(const char *name=NULL, int kind=0);
    NlmeNetworkDiscovery_request(const NlmeNetworkDiscovery_request& other);
    virtual ~NlmeNetworkDiscovery_request();
    NlmeNetworkDiscovery_request& operator=(const NlmeNetworkDiscovery_request& other);
    virtual NlmeNetworkDiscovery_request *dup() const {return new NlmeNetworkDiscovery_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getScanChannels() const;
    virtual void setScanChannels(unsigned int ScanChannels_var);
    virtual unsigned char getScanDuration() const;
    virtual void setScanDuration(unsigned char ScanDuration_var);
};

inline void doPacking(cCommBuffer *b, NlmeNetworkDiscovery_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeNetworkDiscovery_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeNetworkDiscovery_confirm extends NlmeMsg {
 *     unsigned char networkCount;
 *     NetworkDescriptor NetworkDescriptorList[];
 *     unsigned char status enum(MacEnum);
 * };
 * </pre>
 */
class NlmeNetworkDiscovery_confirm : public NlmeMsg
{
  protected:
    unsigned char networkCount_var;
    NetworkDescriptor *NetworkDescriptorList_var; // array ptr
    unsigned int NetworkDescriptorList_arraysize;
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeNetworkDiscovery_confirm&);

  public:
    NlmeNetworkDiscovery_confirm(const char *name=NULL, int kind=0);
    NlmeNetworkDiscovery_confirm(const NlmeNetworkDiscovery_confirm& other);
    virtual ~NlmeNetworkDiscovery_confirm();
    NlmeNetworkDiscovery_confirm& operator=(const NlmeNetworkDiscovery_confirm& other);
    virtual NlmeNetworkDiscovery_confirm *dup() const {return new NlmeNetworkDiscovery_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getNetworkCount() const;
    virtual void setNetworkCount(unsigned char networkCount_var);
    virtual void setNetworkDescriptorListArraySize(unsigned int size);
    virtual unsigned int getNetworkDescriptorListArraySize() const;
    virtual NetworkDescriptor& getNetworkDescriptorList(unsigned int k);
    virtual const NetworkDescriptor& getNetworkDescriptorList(unsigned int k) const {return const_cast<NlmeNetworkDiscovery_confirm*>(this)->getNetworkDescriptorList(k);}
    virtual void setNetworkDescriptorList(unsigned int k, const NetworkDescriptor& NetworkDescriptorList_var);
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, NlmeNetworkDiscovery_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeNetworkDiscovery_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmePermitJoining_request extends NlmeMsg {
 *     unsigned char permitDuration;
 * };
 * </pre>
 */
class NlmePermitJoining_request : public NlmeMsg
{
  protected:
    unsigned char permitDuration_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmePermitJoining_request&);

  public:
    NlmePermitJoining_request(const char *name=NULL, int kind=0);
    NlmePermitJoining_request(const NlmePermitJoining_request& other);
    virtual ~NlmePermitJoining_request();
    NlmePermitJoining_request& operator=(const NlmePermitJoining_request& other);
    virtual NlmePermitJoining_request *dup() const {return new NlmePermitJoining_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getPermitDuration() const;
    virtual void setPermitDuration(unsigned char permitDuration_var);
};

inline void doPacking(cCommBuffer *b, NlmePermitJoining_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmePermitJoining_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmePermitJoining_confirm extends NlmeMsg {
 *     unsigned char status enum(MacEnum);
 * };
 * </pre>
 */
class NlmePermitJoining_confirm : public NlmeMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmePermitJoining_confirm&);

  public:
    NlmePermitJoining_confirm(const char *name=NULL, int kind=0);
    NlmePermitJoining_confirm(const NlmePermitJoining_confirm& other);
    virtual ~NlmePermitJoining_confirm();
    NlmePermitJoining_confirm& operator=(const NlmePermitJoining_confirm& other);
    virtual NlmePermitJoining_confirm *dup() const {return new NlmePermitJoining_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, NlmePermitJoining_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmePermitJoining_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeStartRouter_request extends NlmeMsg {
 *     unsigned char beaconOrder;
 *     unsigned char superframeOrder;
 *     bool batteryLifeExtension;
 * };
 * </pre>
 */
class NlmeStartRouter_request : public NlmeMsg
{
  protected:
    unsigned char beaconOrder_var;
    unsigned char superframeOrder_var;
    bool batteryLifeExtension_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeStartRouter_request&);

  public:
    NlmeStartRouter_request(const char *name=NULL, int kind=0);
    NlmeStartRouter_request(const NlmeStartRouter_request& other);
    virtual ~NlmeStartRouter_request();
    NlmeStartRouter_request& operator=(const NlmeStartRouter_request& other);
    virtual NlmeStartRouter_request *dup() const {return new NlmeStartRouter_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getBeaconOrder() const;
    virtual void setBeaconOrder(unsigned char beaconOrder_var);
    virtual unsigned char getSuperframeOrder() const;
    virtual void setSuperframeOrder(unsigned char superframeOrder_var);
    virtual bool getBatteryLifeExtension() const;
    virtual void setBatteryLifeExtension(bool batteryLifeExtension_var);
};

inline void doPacking(cCommBuffer *b, NlmeStartRouter_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeStartRouter_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeStartRouter_confirm extends NlmeMsg {
 *     unsigned char status enum(MacEnum); 
 * };
 * </pre>
 */
class NlmeStartRouter_confirm : public NlmeMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeStartRouter_confirm&);

  public:
    NlmeStartRouter_confirm(const char *name=NULL, int kind=0);
    NlmeStartRouter_confirm(const NlmeStartRouter_confirm& other);
    virtual ~NlmeStartRouter_confirm();
    NlmeStartRouter_confirm& operator=(const NlmeStartRouter_confirm& other);
    virtual NlmeStartRouter_confirm *dup() const {return new NlmeStartRouter_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, NlmeStartRouter_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeStartRouter_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeJoin_request extends NlmeMsg {
 *     unsigned short panId;
 *     bool joinAsRouter;
 *     bool rejoinNetwork;
 *     unsigned int scanChannels;
 *     unsigned char scanDuration;
 *     bool powerSource;
 *     bool rxOnWhenIdle;
 *     bool macSecurity;
 * };
 * </pre>
 */
class NlmeJoin_request : public NlmeMsg
{
  protected:
    unsigned short panId_var;
    bool joinAsRouter_var;
    bool rejoinNetwork_var;
    unsigned int scanChannels_var;
    unsigned char scanDuration_var;
    bool powerSource_var;
    bool rxOnWhenIdle_var;
    bool macSecurity_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeJoin_request&);

  public:
    NlmeJoin_request(const char *name=NULL, int kind=0);
    NlmeJoin_request(const NlmeJoin_request& other);
    virtual ~NlmeJoin_request();
    NlmeJoin_request& operator=(const NlmeJoin_request& other);
    virtual NlmeJoin_request *dup() const {return new NlmeJoin_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned short getPanId() const;
    virtual void setPanId(unsigned short panId_var);
    virtual bool getJoinAsRouter() const;
    virtual void setJoinAsRouter(bool joinAsRouter_var);
    virtual bool getRejoinNetwork() const;
    virtual void setRejoinNetwork(bool rejoinNetwork_var);
    virtual unsigned int getScanChannels() const;
    virtual void setScanChannels(unsigned int scanChannels_var);
    virtual unsigned char getScanDuration() const;
    virtual void setScanDuration(unsigned char scanDuration_var);
    virtual bool getPowerSource() const;
    virtual void setPowerSource(bool powerSource_var);
    virtual bool getRxOnWhenIdle() const;
    virtual void setRxOnWhenIdle(bool rxOnWhenIdle_var);
    virtual bool getMacSecurity() const;
    virtual void setMacSecurity(bool macSecurity_var);
};

inline void doPacking(cCommBuffer *b, NlmeJoin_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeJoin_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeJoin_indication extends NlmeMsg {
 * };
 * </pre>
 */
class NlmeJoin_indication : public NlmeMsg
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeJoin_indication&);

  public:
    NlmeJoin_indication(const char *name=NULL, int kind=0);
    NlmeJoin_indication(const NlmeJoin_indication& other);
    virtual ~NlmeJoin_indication();
    NlmeJoin_indication& operator=(const NlmeJoin_indication& other);
    virtual NlmeJoin_indication *dup() const {return new NlmeJoin_indication(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, NlmeJoin_indication& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeJoin_indication& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NlmeJoin_confirm extends NlmeMsg {
 *     unsigned char status;
 *     unsigned short networkAddress;
 *     unsigned long extendedPanId;
 *     unsigned char currentChannel;
 * };
 * </pre>
 */
class NlmeJoin_confirm : public NlmeMsg
{
  protected:
    unsigned char status_var;
    unsigned short networkAddress_var;
    unsigned long extendedPanId_var;
    unsigned char currentChannel_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NlmeJoin_confirm&);

  public:
    NlmeJoin_confirm(const char *name=NULL, int kind=0);
    NlmeJoin_confirm(const NlmeJoin_confirm& other);
    virtual ~NlmeJoin_confirm();
    NlmeJoin_confirm& operator=(const NlmeJoin_confirm& other);
    virtual NlmeJoin_confirm *dup() const {return new NlmeJoin_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
    virtual unsigned short getNetworkAddress() const;
    virtual void setNetworkAddress(unsigned short networkAddress_var);
    virtual unsigned long getExtendedPanId() const;
    virtual void setExtendedPanId(unsigned long extendedPanId_var);
    virtual unsigned char getCurrentChannel() const;
    virtual void setCurrentChannel(unsigned char currentChannel_var);
};

inline void doPacking(cCommBuffer *b, NlmeJoin_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NlmeJoin_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message NldeMsg extends cPacket {
 * };
 * </pre>
 */
class NldeMsg : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NldeMsg&);

  public:
    NldeMsg(const char *name=NULL, int kind=0);
    NldeMsg(const NldeMsg& other);
    virtual ~NldeMsg();
    NldeMsg& operator=(const NldeMsg& other);
    virtual NldeMsg *dup() const {return new NldeMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, NldeMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NldeMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeMsg extends cPacket {
 * };
 * </pre>
 */
class MlmeMsg : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeMsg&);

  public:
    MlmeMsg(const char *name=NULL, int kind=0);
    MlmeMsg(const MlmeMsg& other);
    virtual ~MlmeMsg();
    MlmeMsg& operator=(const MlmeMsg& other);
    virtual MlmeMsg *dup() const {return new MlmeMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, MlmeMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeScan_request extends MlmeMsg {
 *     
 *     
 *     
 *     
 *     unsigned char scanType;
 *     unsigned int scanChannels;
 *     unsigned char scanDuration;
 *     unsigned char channelPage;
 *     unsigned char securityLevel;
 *     unsigned char keyIdMode;
 *     unsigned char keySource[];
 *     unsigned char kedyIndex;
 * };
 * </pre>
 */
class MlmeScan_request : public MlmeMsg
{
  protected:
    unsigned char scanType_var;
    unsigned int scanChannels_var;
    unsigned char scanDuration_var;
    unsigned char channelPage_var;
    unsigned char securityLevel_var;
    unsigned char keyIdMode_var;
    unsigned char *keySource_var; // array ptr
    unsigned int keySource_arraysize;
    unsigned char kedyIndex_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeScan_request&);

  public:
    MlmeScan_request(const char *name=NULL, int kind=0);
    MlmeScan_request(const MlmeScan_request& other);
    virtual ~MlmeScan_request();
    MlmeScan_request& operator=(const MlmeScan_request& other);
    virtual MlmeScan_request *dup() const {return new MlmeScan_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getScanType() const;
    virtual void setScanType(unsigned char scanType_var);
    virtual unsigned int getScanChannels() const;
    virtual void setScanChannels(unsigned int scanChannels_var);
    virtual unsigned char getScanDuration() const;
    virtual void setScanDuration(unsigned char scanDuration_var);
    virtual unsigned char getChannelPage() const;
    virtual void setChannelPage(unsigned char channelPage_var);
    virtual unsigned char getSecurityLevel() const;
    virtual void setSecurityLevel(unsigned char securityLevel_var);
    virtual unsigned char getKeyIdMode() const;
    virtual void setKeyIdMode(unsigned char keyIdMode_var);
    virtual void setKeySourceArraySize(unsigned int size);
    virtual unsigned int getKeySourceArraySize() const;
    virtual unsigned char getKeySource(unsigned int k) const;
    virtual void setKeySource(unsigned int k, unsigned char keySource_var);
    virtual unsigned char getKedyIndex() const;
    virtual void setKedyIndex(unsigned char kedyIndex_var);
};

inline void doPacking(cCommBuffer *b, MlmeScan_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeScan_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeScan_confirm extends MlmeMsg {
 *     unsigned char status enum(MacEnum);
 *     unsigned char scanType;
 *     unsigned char channelPage;
 *     unsigned int unscannedChannels;
 *     unsigned int resultListSize;
 *     unsigned char energyDetectList[];
 *     PanDescriptor panDescriptorList[];
 * };
 * </pre>
 */
class MlmeScan_confirm : public MlmeMsg
{
  protected:
    unsigned char status_var;
    unsigned char scanType_var;
    unsigned char channelPage_var;
    unsigned int unscannedChannels_var;
    unsigned int resultListSize_var;
    unsigned char *energyDetectList_var; // array ptr
    unsigned int energyDetectList_arraysize;
    PanDescriptor *panDescriptorList_var; // array ptr
    unsigned int panDescriptorList_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeScan_confirm&);

  public:
    MlmeScan_confirm(const char *name=NULL, int kind=0);
    MlmeScan_confirm(const MlmeScan_confirm& other);
    virtual ~MlmeScan_confirm();
    MlmeScan_confirm& operator=(const MlmeScan_confirm& other);
    virtual MlmeScan_confirm *dup() const {return new MlmeScan_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
    virtual unsigned char getScanType() const;
    virtual void setScanType(unsigned char scanType_var);
    virtual unsigned char getChannelPage() const;
    virtual void setChannelPage(unsigned char channelPage_var);
    virtual unsigned int getUnscannedChannels() const;
    virtual void setUnscannedChannels(unsigned int unscannedChannels_var);
    virtual unsigned int getResultListSize() const;
    virtual void setResultListSize(unsigned int resultListSize_var);
    virtual void setEnergyDetectListArraySize(unsigned int size);
    virtual unsigned int getEnergyDetectListArraySize() const;
    virtual unsigned char getEnergyDetectList(unsigned int k) const;
    virtual void setEnergyDetectList(unsigned int k, unsigned char energyDetectList_var);
    virtual void setPanDescriptorListArraySize(unsigned int size);
    virtual unsigned int getPanDescriptorListArraySize() const;
    virtual PanDescriptor& getPanDescriptorList(unsigned int k);
    virtual const PanDescriptor& getPanDescriptorList(unsigned int k) const {return const_cast<MlmeScan_confirm*>(this)->getPanDescriptorList(k);}
    virtual void setPanDescriptorList(unsigned int k, const PanDescriptor& panDescriptorList_var);
};

inline void doPacking(cCommBuffer *b, MlmeScan_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeScan_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeSet_request extends MlmeMsg {
 *     unsigned char PibAttribute;
 *     unsigned char PibAttributeIndex;
 *     unsigned int PibAttributeValue[];
 * };
 * </pre>
 */
class MlmeSet_request : public MlmeMsg
{
  protected:
    unsigned char PibAttribute_var;
    unsigned char PibAttributeIndex_var;
    unsigned int *PibAttributeValue_var; // array ptr
    unsigned int PibAttributeValue_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeSet_request&);

  public:
    MlmeSet_request(const char *name=NULL, int kind=0);
    MlmeSet_request(const MlmeSet_request& other);
    virtual ~MlmeSet_request();
    MlmeSet_request& operator=(const MlmeSet_request& other);
    virtual MlmeSet_request *dup() const {return new MlmeSet_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getPibAttribute() const;
    virtual void setPibAttribute(unsigned char PibAttribute_var);
    virtual unsigned char getPibAttributeIndex() const;
    virtual void setPibAttributeIndex(unsigned char PibAttributeIndex_var);
    virtual void setPibAttributeValueArraySize(unsigned int size);
    virtual unsigned int getPibAttributeValueArraySize() const;
    virtual unsigned int getPibAttributeValue(unsigned int k) const;
    virtual void setPibAttributeValue(unsigned int k, unsigned int PibAttributeValue_var);
};

inline void doPacking(cCommBuffer *b, MlmeSet_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeSet_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeSet_confirm extends MlmeMsg {
 *     unsigned char status;
 *     unsigned char PibAttribute;
 *     unsigned char PibAttributeIndex;
 * };
 * </pre>
 */
class MlmeSet_confirm : public MlmeMsg
{
  protected:
    unsigned char status_var;
    unsigned char PibAttribute_var;
    unsigned char PibAttributeIndex_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeSet_confirm&);

  public:
    MlmeSet_confirm(const char *name=NULL, int kind=0);
    MlmeSet_confirm(const MlmeSet_confirm& other);
    virtual ~MlmeSet_confirm();
    MlmeSet_confirm& operator=(const MlmeSet_confirm& other);
    virtual MlmeSet_confirm *dup() const {return new MlmeSet_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
    virtual unsigned char getPibAttribute() const;
    virtual void setPibAttribute(unsigned char PibAttribute_var);
    virtual unsigned char getPibAttributeIndex() const;
    virtual void setPibAttributeIndex(unsigned char PibAttributeIndex_var);
};

inline void doPacking(cCommBuffer *b, MlmeSet_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeSet_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeStart_request extends MlmeMsg {
 *     unsigned short PanId;
 *     unsigned char logicalChannel;
 *     unsigned char channelPage;
 *     unsigned int startTime;
 *     unsigned char beaconOrder;
 *     unsigned char superframeOrder;
 *     bool panCoordinator;
 *     bool batteryLifeExtension;
 *     bool coordRealignment;
 *     unsigned char coordRealignSecurityLevel;
 *     unsigned char coordRealignKeyIdMode;
 *     unsigned char coordRealignKeySource[];
 *     unsigned char coordRealignKeyIndex;
 *     unsigned char beaconSecurityLevel;
 *     unsigned char beaconKeyIdMode;
 *     unsigned char beaconKeySource[];
 *     unsigned char beaconKeyIndex; 
 * };
 * </pre>
 */
class MlmeStart_request : public MlmeMsg
{
  protected:
    unsigned short PanId_var;
    unsigned char logicalChannel_var;
    unsigned char channelPage_var;
    unsigned int startTime_var;
    unsigned char beaconOrder_var;
    unsigned char superframeOrder_var;
    bool panCoordinator_var;
    bool batteryLifeExtension_var;
    bool coordRealignment_var;
    unsigned char coordRealignSecurityLevel_var;
    unsigned char coordRealignKeyIdMode_var;
    unsigned char *coordRealignKeySource_var; // array ptr
    unsigned int coordRealignKeySource_arraysize;
    unsigned char coordRealignKeyIndex_var;
    unsigned char beaconSecurityLevel_var;
    unsigned char beaconKeyIdMode_var;
    unsigned char *beaconKeySource_var; // array ptr
    unsigned int beaconKeySource_arraysize;
    unsigned char beaconKeyIndex_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeStart_request&);

  public:
    MlmeStart_request(const char *name=NULL, int kind=0);
    MlmeStart_request(const MlmeStart_request& other);
    virtual ~MlmeStart_request();
    MlmeStart_request& operator=(const MlmeStart_request& other);
    virtual MlmeStart_request *dup() const {return new MlmeStart_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned short getPanId() const;
    virtual void setPanId(unsigned short PanId_var);
    virtual unsigned char getLogicalChannel() const;
    virtual void setLogicalChannel(unsigned char logicalChannel_var);
    virtual unsigned char getChannelPage() const;
    virtual void setChannelPage(unsigned char channelPage_var);
    virtual unsigned int getStartTime() const;
    virtual void setStartTime(unsigned int startTime_var);
    virtual unsigned char getBeaconOrder() const;
    virtual void setBeaconOrder(unsigned char beaconOrder_var);
    virtual unsigned char getSuperframeOrder() const;
    virtual void setSuperframeOrder(unsigned char superframeOrder_var);
    virtual bool getPanCoordinator() const;
    virtual void setPanCoordinator(bool panCoordinator_var);
    virtual bool getBatteryLifeExtension() const;
    virtual void setBatteryLifeExtension(bool batteryLifeExtension_var);
    virtual bool getCoordRealignment() const;
    virtual void setCoordRealignment(bool coordRealignment_var);
    virtual unsigned char getCoordRealignSecurityLevel() const;
    virtual void setCoordRealignSecurityLevel(unsigned char coordRealignSecurityLevel_var);
    virtual unsigned char getCoordRealignKeyIdMode() const;
    virtual void setCoordRealignKeyIdMode(unsigned char coordRealignKeyIdMode_var);
    virtual void setCoordRealignKeySourceArraySize(unsigned int size);
    virtual unsigned int getCoordRealignKeySourceArraySize() const;
    virtual unsigned char getCoordRealignKeySource(unsigned int k) const;
    virtual void setCoordRealignKeySource(unsigned int k, unsigned char coordRealignKeySource_var);
    virtual unsigned char getCoordRealignKeyIndex() const;
    virtual void setCoordRealignKeyIndex(unsigned char coordRealignKeyIndex_var);
    virtual unsigned char getBeaconSecurityLevel() const;
    virtual void setBeaconSecurityLevel(unsigned char beaconSecurityLevel_var);
    virtual unsigned char getBeaconKeyIdMode() const;
    virtual void setBeaconKeyIdMode(unsigned char beaconKeyIdMode_var);
    virtual void setBeaconKeySourceArraySize(unsigned int size);
    virtual unsigned int getBeaconKeySourceArraySize() const;
    virtual unsigned char getBeaconKeySource(unsigned int k) const;
    virtual void setBeaconKeySource(unsigned int k, unsigned char beaconKeySource_var);
    virtual unsigned char getBeaconKeyIndex() const;
    virtual void setBeaconKeyIndex(unsigned char beaconKeyIndex_var);
};

inline void doPacking(cCommBuffer *b, MlmeStart_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeStart_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeStart_confirm extends MlmeMsg {
 *     unsigned char status enum(MacEnum);
 * };
 * </pre>
 */
class MlmeStart_confirm : public MlmeMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeStart_confirm&);

  public:
    MlmeStart_confirm(const char *name=NULL, int kind=0);
    MlmeStart_confirm(const MlmeStart_confirm& other);
    virtual ~MlmeStart_confirm();
    MlmeStart_confirm& operator=(const MlmeStart_confirm& other);
    virtual MlmeStart_confirm *dup() const {return new MlmeStart_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, MlmeStart_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeStart_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeAssociate_request extends MlmeMsg {
 *     unsigned char logicalChannel;
 *     unsigned char channelPage;
 *     unsigned char coordAddrMode;
 *     unsigned short coordPanId;
 *     unsigned long coordAddress;
 * 	bool alternatePanCoordinator;
 * 	bool deviceType;
 * 	bool powerSource;
 * 	bool receiverOnWhenIdle;
 * 	bool securityCapability;
 * 	bool allocateAddress;
 * 	unsigned char securityLevel;
 * 	unsigned char keyIdMode;
 * 	unsigned char keySource[];
 * 	unsigned char keyIndex;
 * };
 * </pre>
 */
class MlmeAssociate_request : public MlmeMsg
{
  protected:
    unsigned char logicalChannel_var;
    unsigned char channelPage_var;
    unsigned char coordAddrMode_var;
    unsigned short coordPanId_var;
    unsigned long coordAddress_var;
    bool alternatePanCoordinator_var;
    bool deviceType_var;
    bool powerSource_var;
    bool receiverOnWhenIdle_var;
    bool securityCapability_var;
    bool allocateAddress_var;
    unsigned char securityLevel_var;
    unsigned char keyIdMode_var;
    unsigned char *keySource_var; // array ptr
    unsigned int keySource_arraysize;
    unsigned char keyIndex_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeAssociate_request&);

  public:
    MlmeAssociate_request(const char *name=NULL, int kind=0);
    MlmeAssociate_request(const MlmeAssociate_request& other);
    virtual ~MlmeAssociate_request();
    MlmeAssociate_request& operator=(const MlmeAssociate_request& other);
    virtual MlmeAssociate_request *dup() const {return new MlmeAssociate_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getLogicalChannel() const;
    virtual void setLogicalChannel(unsigned char logicalChannel_var);
    virtual unsigned char getChannelPage() const;
    virtual void setChannelPage(unsigned char channelPage_var);
    virtual unsigned char getCoordAddrMode() const;
    virtual void setCoordAddrMode(unsigned char coordAddrMode_var);
    virtual unsigned short getCoordPanId() const;
    virtual void setCoordPanId(unsigned short coordPanId_var);
    virtual unsigned long getCoordAddress() const;
    virtual void setCoordAddress(unsigned long coordAddress_var);
    virtual bool getAlternatePanCoordinator() const;
    virtual void setAlternatePanCoordinator(bool alternatePanCoordinator_var);
    virtual bool getDeviceType() const;
    virtual void setDeviceType(bool deviceType_var);
    virtual bool getPowerSource() const;
    virtual void setPowerSource(bool powerSource_var);
    virtual bool getReceiverOnWhenIdle() const;
    virtual void setReceiverOnWhenIdle(bool receiverOnWhenIdle_var);
    virtual bool getSecurityCapability() const;
    virtual void setSecurityCapability(bool securityCapability_var);
    virtual bool getAllocateAddress() const;
    virtual void setAllocateAddress(bool allocateAddress_var);
    virtual unsigned char getSecurityLevel() const;
    virtual void setSecurityLevel(unsigned char securityLevel_var);
    virtual unsigned char getKeyIdMode() const;
    virtual void setKeyIdMode(unsigned char keyIdMode_var);
    virtual void setKeySourceArraySize(unsigned int size);
    virtual unsigned int getKeySourceArraySize() const;
    virtual unsigned char getKeySource(unsigned int k) const;
    virtual void setKeySource(unsigned int k, unsigned char keySource_var);
    virtual unsigned char getKeyIndex() const;
    virtual void setKeyIndex(unsigned char keyIndex_var);
};

inline void doPacking(cCommBuffer *b, MlmeAssociate_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeAssociate_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeAssociate_confirm extends MlmeMsg {
 * };
 * </pre>
 */
class MlmeAssociate_confirm : public MlmeMsg
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeAssociate_confirm&);

  public:
    MlmeAssociate_confirm(const char *name=NULL, int kind=0);
    MlmeAssociate_confirm(const MlmeAssociate_confirm& other);
    virtual ~MlmeAssociate_confirm();
    MlmeAssociate_confirm& operator=(const MlmeAssociate_confirm& other);
    virtual MlmeAssociate_confirm *dup() const {return new MlmeAssociate_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, MlmeAssociate_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeAssociate_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeAssociate_indication extends MlmeMsg {
 *     unsigned long deviceAddress;
 *     bool alternatePanCoordinator;
 * 	bool deviceType;
 * 	bool powerSource;
 * 	bool receiverOnWhenIdle;
 * 	bool securityCapability;
 * 	bool allocateAddress;
 *     unsigned char securityLevel;
 * 	unsigned char keyIdMode;
 * 	unsigned char keySource[];
 * 	unsigned char keyIndex;
 * };
 * </pre>
 */
class MlmeAssociate_indication : public MlmeMsg
{
  protected:
    unsigned long deviceAddress_var;
    bool alternatePanCoordinator_var;
    bool deviceType_var;
    bool powerSource_var;
    bool receiverOnWhenIdle_var;
    bool securityCapability_var;
    bool allocateAddress_var;
    unsigned char securityLevel_var;
    unsigned char keyIdMode_var;
    unsigned char *keySource_var; // array ptr
    unsigned int keySource_arraysize;
    unsigned char keyIndex_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeAssociate_indication&);

  public:
    MlmeAssociate_indication(const char *name=NULL, int kind=0);
    MlmeAssociate_indication(const MlmeAssociate_indication& other);
    virtual ~MlmeAssociate_indication();
    MlmeAssociate_indication& operator=(const MlmeAssociate_indication& other);
    virtual MlmeAssociate_indication *dup() const {return new MlmeAssociate_indication(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getDeviceAddress() const;
    virtual void setDeviceAddress(unsigned long deviceAddress_var);
    virtual bool getAlternatePanCoordinator() const;
    virtual void setAlternatePanCoordinator(bool alternatePanCoordinator_var);
    virtual bool getDeviceType() const;
    virtual void setDeviceType(bool deviceType_var);
    virtual bool getPowerSource() const;
    virtual void setPowerSource(bool powerSource_var);
    virtual bool getReceiverOnWhenIdle() const;
    virtual void setReceiverOnWhenIdle(bool receiverOnWhenIdle_var);
    virtual bool getSecurityCapability() const;
    virtual void setSecurityCapability(bool securityCapability_var);
    virtual bool getAllocateAddress() const;
    virtual void setAllocateAddress(bool allocateAddress_var);
    virtual unsigned char getSecurityLevel() const;
    virtual void setSecurityLevel(unsigned char securityLevel_var);
    virtual unsigned char getKeyIdMode() const;
    virtual void setKeyIdMode(unsigned char keyIdMode_var);
    virtual void setKeySourceArraySize(unsigned int size);
    virtual unsigned int getKeySourceArraySize() const;
    virtual unsigned char getKeySource(unsigned int k) const;
    virtual void setKeySource(unsigned int k, unsigned char keySource_var);
    virtual unsigned char getKeyIndex() const;
    virtual void setKeyIndex(unsigned char keyIndex_var);
};

inline void doPacking(cCommBuffer *b, MlmeAssociate_indication& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeAssociate_indication& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeAssociate_response extends MlmeMsg {
 *     unsigned long deviceAddress;
 *     unsigned short assocShortAddress;
 *     unsigned char status;
 *     unsigned char securityLevel;
 *     unsigned char keyIdMode;
 *     unsigned char keySource[];
 *     unsigned char keyIndex;
 * };
 * </pre>
 */
class MlmeAssociate_response : public MlmeMsg
{
  protected:
    unsigned long deviceAddress_var;
    unsigned short assocShortAddress_var;
    unsigned char status_var;
    unsigned char securityLevel_var;
    unsigned char keyIdMode_var;
    unsigned char *keySource_var; // array ptr
    unsigned int keySource_arraysize;
    unsigned char keyIndex_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeAssociate_response&);

  public:
    MlmeAssociate_response(const char *name=NULL, int kind=0);
    MlmeAssociate_response(const MlmeAssociate_response& other);
    virtual ~MlmeAssociate_response();
    MlmeAssociate_response& operator=(const MlmeAssociate_response& other);
    virtual MlmeAssociate_response *dup() const {return new MlmeAssociate_response(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getDeviceAddress() const;
    virtual void setDeviceAddress(unsigned long deviceAddress_var);
    virtual unsigned short getAssocShortAddress() const;
    virtual void setAssocShortAddress(unsigned short assocShortAddress_var);
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
    virtual unsigned char getSecurityLevel() const;
    virtual void setSecurityLevel(unsigned char securityLevel_var);
    virtual unsigned char getKeyIdMode() const;
    virtual void setKeyIdMode(unsigned char keyIdMode_var);
    virtual void setKeySourceArraySize(unsigned int size);
    virtual unsigned int getKeySourceArraySize() const;
    virtual unsigned char getKeySource(unsigned int k) const;
    virtual void setKeySource(unsigned int k, unsigned char keySource_var);
    virtual unsigned char getKeyIndex() const;
    virtual void setKeyIndex(unsigned char keyIndex_var);
};

inline void doPacking(cCommBuffer *b, MlmeAssociate_response& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeAssociate_response& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MlmeBeaconNotify_indication extends MlmeMsg {
 *     unsigned char bsn;
 *     PanDescriptor panDescriptor;
 *     unsigned char numberOfShortAddressesPending;
 *   	unsigned char numberOfExtendedAddressesPending;
 *   	unsigned long addressList[];
 *   	unsigned int sduLength;
 *   	unsigned int sdu[];
 * };
 * </pre>
 */
class MlmeBeaconNotify_indication : public MlmeMsg
{
  protected:
    unsigned char bsn_var;
    PanDescriptor panDescriptor_var;
    unsigned char numberOfShortAddressesPending_var;
    unsigned char numberOfExtendedAddressesPending_var;
    unsigned long *addressList_var; // array ptr
    unsigned int addressList_arraysize;
    unsigned int sduLength_var;
    unsigned int *sdu_var; // array ptr
    unsigned int sdu_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MlmeBeaconNotify_indication&);

  public:
    MlmeBeaconNotify_indication(const char *name=NULL, int kind=0);
    MlmeBeaconNotify_indication(const MlmeBeaconNotify_indication& other);
    virtual ~MlmeBeaconNotify_indication();
    MlmeBeaconNotify_indication& operator=(const MlmeBeaconNotify_indication& other);
    virtual MlmeBeaconNotify_indication *dup() const {return new MlmeBeaconNotify_indication(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getBsn() const;
    virtual void setBsn(unsigned char bsn_var);
    virtual PanDescriptor& getPanDescriptor();
    virtual const PanDescriptor& getPanDescriptor() const {return const_cast<MlmeBeaconNotify_indication*>(this)->getPanDescriptor();}
    virtual void setPanDescriptor(const PanDescriptor& panDescriptor_var);
    virtual unsigned char getNumberOfShortAddressesPending() const;
    virtual void setNumberOfShortAddressesPending(unsigned char numberOfShortAddressesPending_var);
    virtual unsigned char getNumberOfExtendedAddressesPending() const;
    virtual void setNumberOfExtendedAddressesPending(unsigned char numberOfExtendedAddressesPending_var);
    virtual void setAddressListArraySize(unsigned int size);
    virtual unsigned int getAddressListArraySize() const;
    virtual unsigned long getAddressList(unsigned int k) const;
    virtual void setAddressList(unsigned int k, unsigned long addressList_var);
    virtual unsigned int getSduLength() const;
    virtual void setSduLength(unsigned int sduLength_var);
    virtual void setSduArraySize(unsigned int size);
    virtual unsigned int getSduArraySize() const;
    virtual unsigned int getSdu(unsigned int k) const;
    virtual void setSdu(unsigned int k, unsigned int sdu_var);
};

inline void doPacking(cCommBuffer *b, MlmeBeaconNotify_indication& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MlmeBeaconNotify_indication& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message McpsMsg extends cPacket {
 * };
 * </pre>
 */
class McpsMsg : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const McpsMsg&);

  public:
    McpsMsg(const char *name=NULL, int kind=0);
    McpsMsg(const McpsMsg& other);
    virtual ~McpsMsg();
    McpsMsg& operator=(const McpsMsg& other);
    virtual McpsMsg *dup() const {return new McpsMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, McpsMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, McpsMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MacBeacon extends McpsMsg {
 *   	unsigned char beaconOrder;
 *   	unsigned char superframeOrder;
 *   	unsigned char finalCapSlot;
 *   	bool batteryLifeExtension;
 *   	bool panCoordinator;
 *   	bool associationPermit;
 *   	unsigned char gtsDescriptorCount;
 *   	bool gtsPermit;
 *   	unsigned char directionMask;
 *   	GtsDescriptor gtsList[];
 *   	unsigned char numberOfShortAddressesPending;
 *   	unsigned char numberOfExtendedAddressesPending;
 *   	unsigned long addressList[];
 *   	unsigned int macBeaconPayload[];
 * };
 * </pre>
 */
class MacBeacon : public McpsMsg
{
  protected:
    unsigned char beaconOrder_var;
    unsigned char superframeOrder_var;
    unsigned char finalCapSlot_var;
    bool batteryLifeExtension_var;
    bool panCoordinator_var;
    bool associationPermit_var;
    unsigned char gtsDescriptorCount_var;
    bool gtsPermit_var;
    unsigned char directionMask_var;
    GtsDescriptor *gtsList_var; // array ptr
    unsigned int gtsList_arraysize;
    unsigned char numberOfShortAddressesPending_var;
    unsigned char numberOfExtendedAddressesPending_var;
    unsigned long *addressList_var; // array ptr
    unsigned int addressList_arraysize;
    unsigned int *macBeaconPayload_var; // array ptr
    unsigned int macBeaconPayload_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacBeacon&);

  public:
    MacBeacon(const char *name=NULL, int kind=0);
    MacBeacon(const MacBeacon& other);
    virtual ~MacBeacon();
    MacBeacon& operator=(const MacBeacon& other);
    virtual MacBeacon *dup() const {return new MacBeacon(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getBeaconOrder() const;
    virtual void setBeaconOrder(unsigned char beaconOrder_var);
    virtual unsigned char getSuperframeOrder() const;
    virtual void setSuperframeOrder(unsigned char superframeOrder_var);
    virtual unsigned char getFinalCapSlot() const;
    virtual void setFinalCapSlot(unsigned char finalCapSlot_var);
    virtual bool getBatteryLifeExtension() const;
    virtual void setBatteryLifeExtension(bool batteryLifeExtension_var);
    virtual bool getPanCoordinator() const;
    virtual void setPanCoordinator(bool panCoordinator_var);
    virtual bool getAssociationPermit() const;
    virtual void setAssociationPermit(bool associationPermit_var);
    virtual unsigned char getGtsDescriptorCount() const;
    virtual void setGtsDescriptorCount(unsigned char gtsDescriptorCount_var);
    virtual bool getGtsPermit() const;
    virtual void setGtsPermit(bool gtsPermit_var);
    virtual unsigned char getDirectionMask() const;
    virtual void setDirectionMask(unsigned char directionMask_var);
    virtual void setGtsListArraySize(unsigned int size);
    virtual unsigned int getGtsListArraySize() const;
    virtual GtsDescriptor& getGtsList(unsigned int k);
    virtual const GtsDescriptor& getGtsList(unsigned int k) const {return const_cast<MacBeacon*>(this)->getGtsList(k);}
    virtual void setGtsList(unsigned int k, const GtsDescriptor& gtsList_var);
    virtual unsigned char getNumberOfShortAddressesPending() const;
    virtual void setNumberOfShortAddressesPending(unsigned char numberOfShortAddressesPending_var);
    virtual unsigned char getNumberOfExtendedAddressesPending() const;
    virtual void setNumberOfExtendedAddressesPending(unsigned char numberOfExtendedAddressesPending_var);
    virtual void setAddressListArraySize(unsigned int size);
    virtual unsigned int getAddressListArraySize() const;
    virtual unsigned long getAddressList(unsigned int k) const;
    virtual void setAddressList(unsigned int k, unsigned long addressList_var);
    virtual void setMacBeaconPayloadArraySize(unsigned int size);
    virtual unsigned int getMacBeaconPayloadArraySize() const;
    virtual unsigned int getMacBeaconPayload(unsigned int k) const;
    virtual void setMacBeaconPayload(unsigned int k, unsigned int macBeaconPayload_var);
};

inline void doPacking(cCommBuffer *b, MacBeacon& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MacBeacon& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MacCommand extends McpsMsg {
 *     unsigned char commandType;
 *     unsigned char commandPayload[];
 * };
 * </pre>
 */
class MacCommand : public McpsMsg
{
  protected:
    unsigned char commandType_var;
    unsigned char *commandPayload_var; // array ptr
    unsigned int commandPayload_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacCommand&);

  public:
    MacCommand(const char *name=NULL, int kind=0);
    MacCommand(const MacCommand& other);
    virtual ~MacCommand();
    MacCommand& operator=(const MacCommand& other);
    virtual MacCommand *dup() const {return new MacCommand(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getCommandType() const;
    virtual void setCommandType(unsigned char commandType_var);
    virtual void setCommandPayloadArraySize(unsigned int size);
    virtual unsigned int getCommandPayloadArraySize() const;
    virtual unsigned char getCommandPayload(unsigned int k) const;
    virtual void setCommandPayload(unsigned int k, unsigned char commandPayload_var);
};

inline void doPacking(cCommBuffer *b, MacCommand& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MacCommand& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message MacAck extends McpsMsg {
 *     unsigned char sequenceNumber;
 * };
 * </pre>
 */
class MacAck : public McpsMsg
{
  protected:
    unsigned char sequenceNumber_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacAck&);

  public:
    MacAck(const char *name=NULL, int kind=0);
    MacAck(const MacAck& other);
    virtual ~MacAck();
    MacAck& operator=(const MacAck& other);
    virtual MacAck *dup() const {return new MacAck(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getSequenceNumber() const;
    virtual void setSequenceNumber(unsigned char sequenceNumber_var);
};

inline void doPacking(cCommBuffer *b, MacAck& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MacAck& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeMsg extends cPacket {
 * };
 * </pre>
 */
class PlmeMsg : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeMsg&);

  public:
    PlmeMsg(const char *name=NULL, int kind=0);
    PlmeMsg(const PlmeMsg& other);
    virtual ~PlmeMsg();
    PlmeMsg& operator=(const PlmeMsg& other);
    virtual PlmeMsg *dup() const {return new PlmeMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, PlmeMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeSetTrxState_request extends PlmeMsg {
 *     unsigned char state enum(PhyEnum);
 * };
 * </pre>
 */
class PlmeSetTrxState_request : public PlmeMsg
{
  protected:
    unsigned char state_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeSetTrxState_request&);

  public:
    PlmeSetTrxState_request(const char *name=NULL, int kind=0);
    PlmeSetTrxState_request(const PlmeSetTrxState_request& other);
    virtual ~PlmeSetTrxState_request();
    PlmeSetTrxState_request& operator=(const PlmeSetTrxState_request& other);
    virtual PlmeSetTrxState_request *dup() const {return new PlmeSetTrxState_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getState() const;
    virtual void setState(unsigned char state_var);
};

inline void doPacking(cCommBuffer *b, PlmeSetTrxState_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeSetTrxState_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeSetTrxState_confirm extends PlmeMsg {
 *     unsigned char status enum(PhyEnum);
 * };
 * </pre>
 */
class PlmeSetTrxState_confirm : public PlmeMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeSetTrxState_confirm&);

  public:
    PlmeSetTrxState_confirm(const char *name=NULL, int kind=0);
    PlmeSetTrxState_confirm(const PlmeSetTrxState_confirm& other);
    virtual ~PlmeSetTrxState_confirm();
    PlmeSetTrxState_confirm& operator=(const PlmeSetTrxState_confirm& other);
    virtual PlmeSetTrxState_confirm *dup() const {return new PlmeSetTrxState_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, PlmeSetTrxState_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeSetTrxState_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeSet_request extends PlmeMsg {
 *     unsigned char PibAttribute;
 *     unsigned int PibAttributeValue[];
 * };
 * </pre>
 */
class PlmeSet_request : public PlmeMsg
{
  protected:
    unsigned char PibAttribute_var;
    unsigned int *PibAttributeValue_var; // array ptr
    unsigned int PibAttributeValue_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeSet_request&);

  public:
    PlmeSet_request(const char *name=NULL, int kind=0);
    PlmeSet_request(const PlmeSet_request& other);
    virtual ~PlmeSet_request();
    PlmeSet_request& operator=(const PlmeSet_request& other);
    virtual PlmeSet_request *dup() const {return new PlmeSet_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getPibAttribute() const;
    virtual void setPibAttribute(unsigned char PibAttribute_var);
    virtual void setPibAttributeValueArraySize(unsigned int size);
    virtual unsigned int getPibAttributeValueArraySize() const;
    virtual unsigned int getPibAttributeValue(unsigned int k) const;
    virtual void setPibAttributeValue(unsigned int k, unsigned int PibAttributeValue_var);
};

inline void doPacking(cCommBuffer *b, PlmeSet_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeSet_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeSet_confirm extends PlmeMsg {
 *     unsigned char status;
 *     unsigned char PibAttribute;
 * };
 * </pre>
 */
class PlmeSet_confirm : public PlmeMsg
{
  protected:
    unsigned char status_var;
    unsigned char PibAttribute_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeSet_confirm&);

  public:
    PlmeSet_confirm(const char *name=NULL, int kind=0);
    PlmeSet_confirm(const PlmeSet_confirm& other);
    virtual ~PlmeSet_confirm();
    PlmeSet_confirm& operator=(const PlmeSet_confirm& other);
    virtual PlmeSet_confirm *dup() const {return new PlmeSet_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
    virtual unsigned char getPibAttribute() const;
    virtual void setPibAttribute(unsigned char PibAttribute_var);
};

inline void doPacking(cCommBuffer *b, PlmeSet_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeSet_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeEd_request extends PlmeMsg {
 * };
 * </pre>
 */
class PlmeEd_request : public PlmeMsg
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeEd_request&);

  public:
    PlmeEd_request(const char *name=NULL, int kind=0);
    PlmeEd_request(const PlmeEd_request& other);
    virtual ~PlmeEd_request();
    PlmeEd_request& operator=(const PlmeEd_request& other);
    virtual PlmeEd_request *dup() const {return new PlmeEd_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, PlmeEd_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeEd_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeEd_confirm extends PlmeMsg {
 *     unsigned char status;
 *     unsigned char energyLevel;
 * };
 * </pre>
 */
class PlmeEd_confirm : public PlmeMsg
{
  protected:
    unsigned char status_var;
    unsigned char energyLevel_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeEd_confirm&);

  public:
    PlmeEd_confirm(const char *name=NULL, int kind=0);
    PlmeEd_confirm(const PlmeEd_confirm& other);
    virtual ~PlmeEd_confirm();
    PlmeEd_confirm& operator=(const PlmeEd_confirm& other);
    virtual PlmeEd_confirm *dup() const {return new PlmeEd_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
    virtual unsigned char getEnergyLevel() const;
    virtual void setEnergyLevel(unsigned char energyLevel_var);
};

inline void doPacking(cCommBuffer *b, PlmeEd_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeEd_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeCca_request extends PlmeMsg {
 * };
 * </pre>
 */
class PlmeCca_request : public PlmeMsg
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeCca_request&);

  public:
    PlmeCca_request(const char *name=NULL, int kind=0);
    PlmeCca_request(const PlmeCca_request& other);
    virtual ~PlmeCca_request();
    PlmeCca_request& operator=(const PlmeCca_request& other);
    virtual PlmeCca_request *dup() const {return new PlmeCca_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, PlmeCca_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeCca_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PlmeCca_confirm extends PlmeMsg {
 *     unsigned char status enum(PhyEnum);
 * };
 * </pre>
 */
class PlmeCca_confirm : public PlmeMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlmeCca_confirm&);

  public:
    PlmeCca_confirm(const char *name=NULL, int kind=0);
    PlmeCca_confirm(const PlmeCca_confirm& other);
    virtual ~PlmeCca_confirm();
    PlmeCca_confirm& operator=(const PlmeCca_confirm& other);
    virtual PlmeCca_confirm *dup() const {return new PlmeCca_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, PlmeCca_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlmeCca_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PdMsg extends cPacket {
 *     
 *     
 *     unsigned char frameType enum(FrameType);
 *     bool securityEnabled;
 *     bool framePending;
 *     bool ackRequest;
 *     bool panIdCompression;
 *     unsigned char destinationAddressingMode;
 *     unsigned char frameVersion;
 *     unsigned char sourceAddressingMode;
 *     
 *     unsigned char sequenceNumber;
 *     unsigned short destinationPanIdentifier;
 *     unsigned long destinationAddress;
 *     unsigned short sourcePanIdentifier;
 *     unsigned long sourceAddress;
 *     unsigned char auxiliarySecurityHeader[];
 *     unsigned short fcs;
 * };
 * </pre>
 */
class PdMsg : public cPacket
{
  protected:
    unsigned char frameType_var;
    bool securityEnabled_var;
    bool framePending_var;
    bool ackRequest_var;
    bool panIdCompression_var;
    unsigned char destinationAddressingMode_var;
    unsigned char frameVersion_var;
    unsigned char sourceAddressingMode_var;
    unsigned char sequenceNumber_var;
    unsigned short destinationPanIdentifier_var;
    unsigned long destinationAddress_var;
    unsigned short sourcePanIdentifier_var;
    unsigned long sourceAddress_var;
    unsigned char *auxiliarySecurityHeader_var; // array ptr
    unsigned int auxiliarySecurityHeader_arraysize;
    unsigned short fcs_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PdMsg&);

  public:
    PdMsg(const char *name=NULL, int kind=0);
    PdMsg(const PdMsg& other);
    virtual ~PdMsg();
    PdMsg& operator=(const PdMsg& other);
    virtual PdMsg *dup() const {return new PdMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getFrameType() const;
    virtual void setFrameType(unsigned char frameType_var);
    virtual bool getSecurityEnabled() const;
    virtual void setSecurityEnabled(bool securityEnabled_var);
    virtual bool getFramePending() const;
    virtual void setFramePending(bool framePending_var);
    virtual bool getAckRequest() const;
    virtual void setAckRequest(bool ackRequest_var);
    virtual bool getPanIdCompression() const;
    virtual void setPanIdCompression(bool panIdCompression_var);
    virtual unsigned char getDestinationAddressingMode() const;
    virtual void setDestinationAddressingMode(unsigned char destinationAddressingMode_var);
    virtual unsigned char getFrameVersion() const;
    virtual void setFrameVersion(unsigned char frameVersion_var);
    virtual unsigned char getSourceAddressingMode() const;
    virtual void setSourceAddressingMode(unsigned char sourceAddressingMode_var);
    virtual unsigned char getSequenceNumber() const;
    virtual void setSequenceNumber(unsigned char sequenceNumber_var);
    virtual unsigned short getDestinationPanIdentifier() const;
    virtual void setDestinationPanIdentifier(unsigned short destinationPanIdentifier_var);
    virtual unsigned long getDestinationAddress() const;
    virtual void setDestinationAddress(unsigned long destinationAddress_var);
    virtual unsigned short getSourcePanIdentifier() const;
    virtual void setSourcePanIdentifier(unsigned short sourcePanIdentifier_var);
    virtual unsigned long getSourceAddress() const;
    virtual void setSourceAddress(unsigned long sourceAddress_var);
    virtual void setAuxiliarySecurityHeaderArraySize(unsigned int size);
    virtual unsigned int getAuxiliarySecurityHeaderArraySize() const;
    virtual unsigned char getAuxiliarySecurityHeader(unsigned int k) const;
    virtual void setAuxiliarySecurityHeader(unsigned int k, unsigned char auxiliarySecurityHeader_var);
    virtual unsigned short getFcs() const;
    virtual void setFcs(unsigned short fcs_var);
};

inline void doPacking(cCommBuffer *b, PdMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PdMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PdData_request extends PdMsg {
 *     unsigned int psduLength;
 * };
 * </pre>
 */
class PdData_request : public PdMsg
{
  protected:
    unsigned int psduLength_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PdData_request&);

  public:
    PdData_request(const char *name=NULL, int kind=0);
    PdData_request(const PdData_request& other);
    virtual ~PdData_request();
    PdData_request& operator=(const PdData_request& other);
    virtual PdData_request *dup() const {return new PdData_request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPsduLength() const;
    virtual void setPsduLength(unsigned int psduLength_var);
};

inline void doPacking(cCommBuffer *b, PdData_request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PdData_request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PdData_confirm extends PdMsg {
 *     unsigned char status enum(PhyEnum);
 * };
 * </pre>
 */
class PdData_confirm : public PdMsg
{
  protected:
    unsigned char status_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PdData_confirm&);

  public:
    PdData_confirm(const char *name=NULL, int kind=0);
    PdData_confirm(const PdData_confirm& other);
    virtual ~PdData_confirm();
    PdData_confirm& operator=(const PdData_confirm& other);
    virtual PdData_confirm *dup() const {return new PdData_confirm(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status_var);
};

inline void doPacking(cCommBuffer *b, PdData_confirm& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PdData_confirm& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message PdData_indication extends PdMsg {
 *     unsigned char psduLength;
 *     unsigned char ppduLinkQuality;
 * };
 * </pre>
 */
class PdData_indication : public PdMsg
{
  protected:
    unsigned char psduLength_var;
    unsigned char ppduLinkQuality_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PdData_indication&);

  public:
    PdData_indication(const char *name=NULL, int kind=0);
    PdData_indication(const PdData_indication& other);
    virtual ~PdData_indication();
    PdData_indication& operator=(const PdData_indication& other);
    virtual PdData_indication *dup() const {return new PdData_indication(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getPsduLength() const;
    virtual void setPsduLength(unsigned char psduLength_var);
    virtual unsigned char getPpduLinkQuality() const;
    virtual void setPpduLinkQuality(unsigned char ppduLinkQuality_var);
};

inline void doPacking(cCommBuffer *b, PdData_indication& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PdData_indication& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg</tt> by opp_msgc.
 * <pre>
 * message Frame802154 extends cPacket {
 *     
 * };
 * </pre>
 */
class Frame802154 : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Frame802154&);

  public:
    Frame802154(const char *name=NULL, int kind=0);
    Frame802154(const Frame802154& other);
    virtual ~Frame802154();
    Frame802154& operator=(const Frame802154& other);
    virtual Frame802154 *dup() const {return new Frame802154(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, Frame802154& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Frame802154& obj) {obj.parsimUnpack(b);}


#endif // _MESSAGES_M_H_
